spring:
  application:
    name: auth-service
  datasource:
    # url: jdbc:postgresql://db:5432/auth_service_db
    url: jdbc:postgresql://localhost:5432/auth_service_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8081