spring:
  application:
    name: auth-service
  datasource:
    # url: jdbc:postgresql://db:5432/auth_service_db
    url: jdbc:postgresql://localhost:5432/auth_service_db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
  cloud:
    config:
      uri: http://localhost:8888

security:
  jwtSecret: your-secret-key

server:
  port: 8082