spring:
  application:
    name: analytics-service
  datasource:
    # url: jdbc:postgresql://db:5432/analytics_service_db
    url: jdbc:postgresql://localhost:5432/analytics_service_db
    username: postgres
    password: root
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8080