spring:
  application:
    name: posts-service
  datasource:
    driverClassName: org.postgresql.Driver
    #   url: jdbc:postgresql://db:5432/post_service_db
    url: jdbc:postgresql://localhost:5432/post_service_db
    username: postgres
    password: root
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888

post:
  max:
    length: 25

api:
  secret: your-very-long-base64-encoded-secret-key-of-at-least-32-bytes

server:
  port: 8084